server:
  port: 9090

spring:
  profiles:
    active: dev
  #ehcache
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  #mail
  mail:
    host: smtp.exmail.qq.com
    username: fengyw@roncoo.com,service@roncoo.com,education@roncoo.com
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true

#文件上传
http:
  multipart:
    #默认支持文件上传.
    enabled: true
    #支持文件写入磁盘.
    file-size-threshold: 0
    #最大支持文件大小
    max-file-size: 2Mb
    #最大支持请求大小
    max-request-size: 10Mb

mybatis-plus:
  # resource的classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mappers/*Mapper.xml
  #别名
  typeAliasesPackage: com.tulin.platform_model.model
  global-config:
    #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 2
    #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
    field-strategy: NOT_EMPTY
    #下划线
    db-column-underline: true
    #mapper
    refresh-mapper: true
  configuration:
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
wx:
  open:
    config:
      # 填写自己的 appid
      appid: xxxxxxxxxxxxxxxxxxxxxxx
      # 填写自己的 secret
      secret: xxxxxxxxxxxxxxxxxxxxxxxxx
      redirectUrl: http://www.xxx.com/wxCallBack
      csrfKey: WeChat_WxJava_Demo




